version: '3.8'

services:
  database:
    image: postgres
    container_name: test_db
    networks:
      - mynet
    environment:
      - POSTGRES_PASSWORD=188651
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST_AUTH_METHOD=md5
    ports:
      - '5400:5432'

networks:
  mynet:
    driver: bridge